### ISSUE TITLE
drag&drop crash

### ISSUE THREAD

**Issue by christianrauch** [flathub/org.gnome.gitlab.YaLTeR.VideoTrimmer#2]
When I drag&drop a video into the app, it states that the file does not exist. I assume that issue is related to sandbox restrictions that have to be set/granted properly.

However, if I acknowledge the dialog with "OK" the app closes/asserst/crashes with
```
(video-trimmer:47): VideoTrimmer-WARNING **: 23:50:43.977: src/video_preview.rs:142: Error in MediaFile: Failed to pause
```

**Comment by YaLTeR** [comment]
Yeah, this is currently an unfortunate restriction with drag&drop: while GTK 4 implements the necessary portal, GTK 3 (on the host file manager side) doesn't. So for drag&drop to work you need to give Video Trimmer the `filesystem=home` or `filesystem=host` permission (e.g. using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal)).

The app closing upon this error is intentional and guided by some code architecture decisions, but I want to change that in the future.

**Comment by christianrauch** [comment]
Could these permissions (e.g. `filesystem=home`) be added to the flatpak manifest? I think it would be nice if you could just drag&drop for a quick video edit.

**Comment by YaLTeR** [comment]
They could, but honestly I don't think that at this point the added convenience outweighs the lower security by default, especially since users can manually set it themselves. Besides, as I understand, as soon as nautilus is ported to GTK 4 (hopefully at a point not too far into the future) DnD will just start working.

**Comment by YaLTeR** [comment]
Also what I do is right click in nautilus and Open With -> Video Trimmer. This way it's almost as fast.
